// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLC3676L0LI5GDC38rpkpePVkQ4oWQak',
    appId: '1:352028414871:android:60bdbb841d2c424034aad2',
    messagingSenderId: '352028414871',
    projectId: 'grade-book-99d84',
    databaseURL:
        'https://grade-book-99d84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grade-book-99d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjl0YvPYpMxVC9gDqQ1M4-nZ32MNBE280',
    appId: '1:352028414871:ios:e2d958fc65bd1b8134aad2',
    messagingSenderId: '352028414871',
    projectId: 'grade-book-99d84',
    databaseURL:
        'https://grade-book-99d84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grade-book-99d84.firebasestorage.app',
    androidClientId:
        '352028414871-e1tue5gsgstjlp5fmo160beffhomlkv5.apps.googleusercontent.com',
    iosClientId:
        '352028414871-2gje4dsr2kt6vth8v399a9go9jpttj0t.apps.googleusercontent.com',
    iosBundleId: 'com.zolina.gradeBook',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB42fLLAzvcVlbbVlL0iF_mf8tferzorlc',
    appId: '1:352028414871:web:8e353ae433a9cabb34aad2',
    messagingSenderId: '352028414871',
    projectId: 'grade-book-99d84',
    authDomain: 'grade-book-99d84.firebaseapp.com',
    databaseURL:
        'https://grade-book-99d84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grade-book-99d84.firebasestorage.app',
    measurementId: 'G-GEPT4612YR',
  );
}
